classdef td
    properties (Constant, Access = private)
        client_id = ' ';
        refresh_token = ' '; 
        callback_url = ' '
        account_id = ' ';
        web_options = td.start()
        
    end
    methods(Static, Access = private)         
        function web_options = start()
            
            urlrefresh_token = urlencode(td.refresh_token);
            url = 'https://api.tdameritrade.com/v1/oauth2/token';

            data = [...
                '&grant_type=','refresh_token',... 
                '&refresh_token=',urlrefresh_token,...
                '&access_type=',...
                '&code=',...
                '&client_id=',td.client_id,'%40AMER.OAUTHAP',...
                '&redirect_uri='] ;

            response = webwrite(url,data);
            access_token = response.access_token;
            %refresh_time = ((datetime('now'))+2/24/4); 
            
            HeaderFields = {'Authorization',['Bearer ',access_token]};
            web_options = weboptions('HeaderFields',HeaderFields,'ContentType','json');
        end
     end
    methods(Static) 
        function [instrument_search] = search(search_details, search_type)
        url = 'https://api.tdameritrade.com/v1/instruments';
                        
        instrument_search = webread(url,...
        'apikey',td.client_id,...
        'symbol',search_details,...
        'projection', search_type,...
         td.web_options);
        end
        function [cusip_search] = cusipSearch(search_details)
            url = ['https://api.tdameritrade.com/v1/instruments/',search_details];
            
            cusip_search = webread(url,...
                'apikey',td.client_id,...
                td.web_options);
        end
        function markethours = multipleMarketHours(search)
            url = 'https://api.tdameritrade.com/v1/marketdata/hours';
            
            markethours = webread(url,...
                'apikey',td.client_id,...
                'markets', search,...
                'date',datestr(datenum(datestr(datetime('today')),'dd-mm-yyyy'),'yyyy-mm-dd'),...
                td.web_options);
        end
        function markethours = singleMarketHours(search)
            url = ['https://api.tdameritrade.com/v1/marketdata/',search,'/hours'];
            
            markethours = webread(url,...
                'apikey',td.client_id,...
                'markets', search,...
                'date',datestr(datenum(datestr(datetime('today')),'dd-mm-yyyy'),'yyyy-mm-dd'),...
                td.web_options);
        end
        function movers = getMovers(search,direction,change)
            url = ['https://api.tdameritrade.com/v1/marketdata/',search,'/movers'];
            
            movers = webread(url,...
                'apikey',td.client_id,...
                'direction',direction,...
                'change',change,...
                td.web_options);
        end
        function [optionschain] = tdOptionsChain(symbol,contractType,strikeCount,includeQuotes,strategy,interval,strike,range)
            url =  'https://api.tdameritrade.com/v1/marketdata/chains';
            optionschain = webread(url,...
                'apikey',td.client_id,...
                'symbol',symbol,...
                'contractType',contractType,...
                'strikeCount',strikeCount,...
                'includeQuotes',includeQuotes,...
                'Strategy',strategy,...
                'interval',interval,...
                'strike',strike,...
                'range',range,...
                'fromDate',TD_Structure.fromDate,...
                'toDate',TD_Structure.toDate,...
                'expMonth',TD_Structure.expMonth,...
                'optionType',TD_Structure.optionType,td.web_options);
        end
        function pricehistory = getPriceHistory(symbol,periodType,frequencyType,frequency,endDate,startDate,needExtendedHoursData)
            url = ['https://api.tdameritrade.com/v1/marketdata/',symbol,'/pricehistory'];
            
            pricehistory = webread(url,...
                'apikey',td.client_id,...
                'periodType',periodType,...
                'period',period,...
                'frequencyType',frequencyType,...
                'frequency',frequency,...
                'endDate',endDate,...
                'startDate',startDate,...
                'needExtendedHoursData',needExtendedHoursData,...
                td.web_options);
        end
        function quote = getQuote(symbol)
            url = ['https://api.tdameritrade.com/v1/marketdata/',symbol,'/quotes'];
            
            quote = webread(url,...
                'apikey',td.client_id,...
                td.web_options);
        end
        function quotes = getQuotes(symbol)
            url = 'https://api.tdameritrade.com/v1/marketdata/quotes';
            
            quotes = webread(url,...
                'apikey',td.client_id,...
                'symbol',symbol,...
                td.web_options);
        end
    end
        
end