tdStruct = struct('symbol','PLTR',...
    'periodType', 'day',...
    'period','2',...
    'frequencyType','minute',...
    'frequency','1',...
    'endDate',(num2str(posixtime(datetime('now'))*1e3)),...
    'startDate','',...
    'needExtendedHoursData','true',...
    'contract_type','ALL',...
    'strike_count','200',...
    'include_quotes','TRUE',...
    'strategy','SINGLE',...
    'interval','1',...
    'range','all',...
    'fromDate',datetime('now','Format','yyyy-MM-dd'),...
    'toDate',datetime('now','Format','yyyy-MM-dd')+37,...
    'expMonth','ALL',...
    'optionType','ALL',...
    'fields','streamerSubscriptionKeys,streamerConnectionInfo'...
    );