function [pricehistory] = tdPriceHistory(tdStruct,client_details,options)
    url = ['https://api.tdameritrade.com/v1/marketdata/',tdStruct.symbol,'/pricehistory'];
   
    pricehistory = webread(url,...
        'apikey',client_details.client_id,...
        'periodType',tdStruct.periodType,...
        'period',tdStruct.period,...
        'frequencyType',tdStruct.frequencyType,...
        'frequency',tdStruct.frequency,...
        'endDate',tdStruct.endDate,...
        'needExtendedHoursData',tdStruct.needExtendedHoursData,...
        options);


end