function [instrument_search] = tdSearch(search_details,projection,client_details, weboptions)
    url = 'https://api.tdameritrade.com/v1/instruments';
    
    instrument_search = webread(url,...
    'apikey',client_details.client_id,...
    'symbol',search_details,...
    'projection', projection,...
    weboptions);
end